openapi: 3.0.3
info:
  title: Überböse Management API
  description: |
    API endpoints for managing Spotify account authentication and integration
  version: 1.0.0

paths:
  /mgmt/spotify/init:
    post:
      summary: Initialize Spotify OAuth flow
      description: |
        Initiates the Spotify OAuth authentication flow.
        Returns a redirect URL that should be opened in a browser for the user to authenticate with Spotify.
        The API will handle the returnUrl automatically if not provided.
      operationId: initSpotifyAuth
      tags:
        - Spotify Management
      responses:
        '200':
          description: Successfully initialized Spotify OAuth flow
          content:
            application/json:
              schema:
                type: object
                required:
                  - redirectUrl
                properties:
                  redirectUrl:
                    type: string
                    format: uri
                    description: The Spotify OAuth URL that should be opened in a browser
                    example: "https://accounts.spotify.com/authorize?client_id=xxx&response_type=code&redirect_uri=xxx&scope=user-read-private"
              examples:
                success:
                  summary: Successful response
                  value:
                    redirectUrl: "https://accounts.spotify.com/authorize?client_id=abc123&response_type=code&redirect_uri=https%3A%2F%2Fapi.example.com%2Fcallback&scope=user-read-private%20user-read-email"
        '400':
          description: Bad request - Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                invalidReturnUrl:
                  summary: Invalid return URL format
                  value:
                    error: "Invalid return URL format"
                    message: "The provided returnUrl is not a valid URI"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                serverError:
                  summary: Server error
                  value:
                    error: "Internal server error"
                    message: "Failed to initialize Spotify authentication"

  /mgmt/spotify/confirm:
    post:
      summary: Confirm Spotify OAuth authentication
      description: |
        Completes the Spotify OAuth flow by exchanging the authorization code
        for access tokens and storing the authenticated Spotify account.
      operationId: confirmSpotifyAuth
      tags:
        - Spotify Management
      parameters:
        - name: code
          in: query
          required: true
          description: The authorization code received from Spotify OAuth callback
          schema:
            type: string
            example: "AQBxVGqZ9..."
      responses:
        '200':
          description: Successfully confirmed and stored Spotify authentication
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Spotify account connected successfully"
                  accountId:
                    type: string
                    description: The unique identifier for the connected Spotify account
                    example: "spotify_user_123"
              examples:
                success:
                  summary: Successful confirmation
                  value:
                    success: true
                    message: "Spotify account connected successfully"
                    accountId: "spotify_user_abc123"
        '400':
          description: Bad request - Invalid or missing authorization code
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                missingCode:
                  summary: Missing authorization code
                  value:
                    error: "Missing parameter"
                    message: "Authorization code is required"
                invalidCode:
                  summary: Invalid authorization code
                  value:
                    error: "Invalid code"
                    message: "The provided authorization code is invalid or expired"
        '401':
          description: Unauthorized - Failed to authenticate with Spotify
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                authFailed:
                  summary: Authentication failed
                  value:
                    error: "Authentication failed"
                    message: "Failed to exchange authorization code with Spotify"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                serverError:
                  summary: Server error
                  value:
                    error: "Internal server error"
                    message: "Failed to confirm Spotify authentication"

  /mgmt/spotify/entity:
    post:
      summary: Get Spotify entity information
      description: |
        Retrieves name and image URL for a Spotify entity (track, album, artist, or playlist).
        Accepts a Spotify URI and returns the entity's display name and a medium-sized image URL.
      operationId: getSpotifyEntity
      tags:
        - Spotify Management
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - uri
              properties:
                uri:
                  type: string
                  description: Spotify URI (e.g., spotify:track:xxx, spotify:album:xxx, spotify:artist:xxx, spotify:playlist:xxx)
                  example: "spotify:track:6rqhFgbbKwnb9MLmUQDhG6"
            examples:
              track:
                summary: Track URI
                value:
                  uri: "spotify:track:6rqhFgbbKwnb9MLmUQDhG6"
              album:
                summary: Album URI
                value:
                  uri: "spotify:album:4LH4d3cOWNNsVw41Gqt2kv"
              artist:
                summary: Artist URI
                value:
                  uri: "spotify:artist:0OdUWJ0sBjDrqHygGUXeCF"
              playlist:
                summary: Playlist URI
                value:
                  uri: "spotify:playlist:37i9dQZF1DXcBWIGoYBM5M"
      responses:
        '200':
          description: Successfully retrieved entity information
          content:
            application/json:
              schema:
                type: object
                required:
                  - name
                properties:
                  name:
                    type: string
                    description: Display name of the entity
                    example: "Bohemian Rhapsody"
                  imageUrl:
                    type: string
                    description: URL to medium-sized image (null if no image available)
                    example: "https://i.scdn.co/image/ab67616d00001e02e319baafd16e84f0408af2a0"
              examples:
                withImage:
                  summary: Entity with image
                  value:
                    name: "Bohemian Rhapsody"
                    imageUrl: "https://i.scdn.co/image/ab67616d00001e02e319baafd16e84f0408af2a0"
                withoutImage:
                  summary: Entity without image
                  value:
                    name: "My Private Playlist"
                    imageUrl: null
        '400':
          description: Invalid URI format or unsupported entity type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                invalidFormat:
                  summary: Invalid URI format
                  value:
                    error: "Invalid URI"
                    message: "The provided URI is not a valid Spotify URI"
                unsupportedType:
                  summary: Unsupported entity type
                  value:
                    error: "Unsupported entity type"
                    message: "Only track, album, artist, and playlist URIs are supported"
        '404':
          description: Entity not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                notFound:
                  summary: Entity not found
                  value:
                    error: "Not found"
                    message: "The specified Spotify entity could not be found"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                serverError:
                  summary: Server error
                  value:
                    error: "Internal server error"
                    message: "Failed to retrieve Spotify entity information"

  /mgmt/spotify/accounts:
    get:
      summary: List all Spotify accounts
      description: |
        Retrieves a list of all connected Spotify accounts.
        Returns only the display name and creation date for each account.
      operationId: listSpotifyAccounts
      tags:
        - Spotify Management
      responses:
        '200':
          description: Successfully retrieved list of Spotify accounts
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListSpotifyAccounts200Response'
              examples:
                withAccounts:
                  summary: Response with multiple accounts
                  value:
                    accounts:
                      - spotifyUserId: "user1"
                        displayName: "John Doe"
                        createdAt: "2025-12-23T10:30:00Z"
                      - spotifyUserId: "user2"
                        displayName: "Jane Smith"
                        createdAt: "2025-12-22T14:15:00Z"
                emptyList:
                  summary: Response with no accounts
                  value:
                    accounts: []
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                serverError:
                  summary: Server error
                  value:
                    error: "Internal server error"
                    message: "Failed to retrieve Spotify accounts"

  /mgmt/accounts/{accountId}/speakers:
    get:
      summary: List speakers for an account
      description: |
        Retrieves a list of speakers (devices) associated with an account.
        Returns the IP address for each speaker found in the account data.
      operationId: listSpeakers
      tags:
        - Account Management
      parameters:
        - name: accountId
          in: path
          required: true
          description: The account ID to retrieve speakers for
          schema:
            type: string
            example: "6921042"
      responses:
        '200':
          description: Successfully retrieved list of speakers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListSpeakers200Response'
              examples:
                withSpeakers:
                  summary: Response with multiple speakers
                  value:
                    speakers:
                      - ipAddress: "192.168.1.100"
                      - ipAddress: "192.168.1.101"
                emptyList:
                  summary: Response with no speakers
                  value:
                    speakers: []
        '404':
          description: Account not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                notFound:
                  summary: Account not found
                  value:
                    error: "Not found"
                    message: "Account data not found for the specified account ID"

components:
  schemas:
    Error:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: A short error code or identifier
          example: "invalid_request"
        message:
          type: string
          description: A human-readable error message
          example: "The request was invalid"
        details:
          type: object
          description: Additional error details (optional)
          additionalProperties: true

    SpotifyAccountListItem:
      type: object
      required:
        - displayName
        - createdAt
        - spotifyUserId
      properties:
        spotifyUserId:
          type: string
          description: The Spotify user ID
          example: "user1"
        displayName:
          type: string
          description: The display name of the Spotify user
          example: "John Doe"
        createdAt:
          type: string
          format: date-time
          description: The timestamp when the account was connected
          example: "2025-12-23T10:30:00Z"

    ListSpotifyAccounts200Response:
      type: object
      required:
        - accounts
      properties:
        accounts:
          type: array
          description: List of connected Spotify accounts
          items:
            $ref: '#/components/schemas/SpotifyAccountListItem'

    Speaker:
      type: object
      required:
        - ipAddress
      properties:
        ipAddress:
          type: string
          description: IP address of the speaker
          example: "192.168.1.100"

    ListSpeakers200Response:
      type: object
      required:
        - speakers
      properties:
        speakers:
          type: array
          description: List of speakers/devices
          items:
            $ref: '#/components/schemas/Speaker'

tags:
  - name: Spotify Management
    description: Endpoints for managing Spotify account authentication and integration
  - name: Account Management
    description: Endpoints for managing account data and devices
