CREATE TABLE IF NOT EXISTS DEVICE (
    DEVICE_ID VARCHAR(255) PRIMARY KEY,
    IP_ADDRESS VARCHAR(45) NOT NULL,
    FIRST_SEEN TIMESTAMP WITH TIME ZONE NOT NULL,
    LAST_SEEN TIMESTAMP WITH TIME ZONE NOT NULL,
    VERSION BIGINT NOT NULL DEFAULT 0
);
