ALTER TABLE DEVICE ADD COLUMN FIRMWARE_VERSION VARCHAR(255);
ALTER TABLE DEVICE ADD COLUMN DEVICE_SERIAL_NUMBER VARCHAR(255);
ALTER TABLE DEVICE ADD COLUMN PRODUCT_CODE VARCHAR(255);
ALTER TABLE DEVICE ADD COLUMN PRODUCT_TYPE VARCHAR(255);
ALTER TABLE DEVICE ADD COLUMN PRODUCT_SERIAL_NUMBER VARCHAR(255);
